# Generated by Django 5.1.3 on 2024-11-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribute', '0002_obituary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obituary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='obituaries/'),
        ),
        migrations.AlterField(
            model_name='obituary',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='obituary',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
